# 標準偏差でハイリスク・ハイリターンも理解できる
```{r}
#| label: setup
#| echo: false
#| warning: false
#| message: false
source("./R/setup.R")
```

## ハイリスク・ハイリターンとローリスク・ローリターン

　ボラティリティとは株の収益率の標準偏差（SD）のことで、収益率は標準偏差分の変動（$\pm SD$）が起きるので、それをリスクとして認識すべきです。  

```{r}
#| code-summary: "P60図表6−1"
"./data/P60_図表6-1.csv" %>% 
  read.csv()
```

　各金融商品の標準偏差（リスク）と平均値（リターン）は下表のようになります。このデータでの標準偏差（リスク）は標本標準偏差ではないことに注意してください。
```{r}
#| code-summary: "P60図表6−1のリスクとリターン"

リスク <- "./data/P60_図表6-1.csv" %>% 
  read.csv() %>% 
  dplyr::summarise(dplyr::across(.cols = tidyselect::starts_with("商品"),
                                 .fns = sd)) %>% 
  round(digits = 1)
リスク

リターン <- "./data/P60_図表6-1.csv" %>% 
  read.csv() %>% 
  dplyr::summarise(dplyr::across(.cols = tidyselect::starts_with("商品"),
                                 .fns = mean)) %>% 
  round(digits = 1)
リターン
```
　  
　このようにリターンの大きな商品はリスクも大きい、ハイリスク・ハイリターンであることが分かります。

```{r}
#| code-summary: ""
risk <- リスク %>% 
  tidyr::pivot_longer(cols = dplyr::everything(),
                      names_to = "商品", values_to = "リスク")

return <- リターン %>% 
  tidyr::pivot_longer(cols = dplyr::everything(),
                      names_to = "商品", values_to = "リターン")

risk %>% 
  dplyr::left_join(return, by = "商品") %>% 
  ggplot2::ggplot(ggplot2::aes(x = リスク, y = リターン, label = 商品)) + 
    ggplot2::geom_point() + 
    ggplot2::geom_smooth(se = FALSE, method = "lm", size = 0.5) +
    ggrepel::geom_text_repel()
```



　  

## 金融商品の優劣の測り方

投信総合検索ライブラリ
https://toushin-lib.fwg.ne.jp/FdsWeb/

```{r}
"https://www.wam.abic.co.jp/contents/C130122/wam3/1/pc/funddtilprice.html?_com_id_session=02202205280131075947&date=202205281752&_biz_id_itcode=”A0331309A&id_src_screen=91101001&_biz_displayterm=3"

"https://www.wam.abic.co.jp/contents/C130122/wam3/1/pc/funddtilprice.html?_com_id_session=02202205280131075947&date=20220528”1752&_biz_id_itcode=A01312103&id_src_screen=91101001&_biz_displayterm=3"

url1 <- ""

xpath <- '//*[@id="fund-price"]/div/ul[2]/li/div[2]/table[2]'



url1 <- "https://kabutan.jp/stock/kabuka?code="
url2 <- "&ashi=mon&page="
pages <- c(1:5)
xpath <- '//*[@id="stock_kabuka_table"]/table[2]'
code = c(7201, 7203, 7211, 7261, 7267, 7270)

tidyr::crossing(code, pages) %>% 
  dplyr::mutate(url = paste0(url1, code, url2, pages)) %>% 
  # dplyr::select(-pages) %>% 
  purrr::pmap_df(.f = function(url, code, pages) {
    xml2::read_html(url) %>% 
      rvest::html_element(xpath = xpath) %>%
      rvest::html_table(header = FALSE) %>%
      dplyr::slice(-1) %>% 
      dplyr::mutate(code = code, page = pages)
  })
```


　SMBC日興証券の[取扱ファンド一覧](https://fund2.smbcnikko.co.jp/smbc_nikko_fund/qsearch.exe?F=list_kokunai&KEY3=101)の各カテゴリの一番はじめにある商品のデータを取得します。
```{r}
url <- "https://fund2.smbcnikko.co.jp/smbc_nikko_fund/qsearch.exe?F=detail_kokunai1&KEY1="
code <- c("9C311125", "39312149", "9K31419A", "32315984", "4931112B",
          "3231203C", "0431218A", "39312149", "42311081", "79314144")
```

```{r}
#| code-summary: "累積リターン"
xpath <- '//*[@id="main"]/section/section[3]/section[2]/div/div[1]/div/table'

return <- tidyr::crossing(url, code) %>% 
  dplyr::mutate(site = paste0(url, code)) %>% 
  dplyr::select(code, site) %>% 
  purrr::pmap_df(.f = function (code, site) {
    xml2::read_html(site) %>% 
      rvest::html_element(xpath = xpath) %>% 
      rvest::html_table(header = FALSE) %>% 
      dplyr::slice(-1) %>% 
      dplyr::mutate(code = code)
  })

return %>% 
  dplyr::select(-(X5:X8)) %>% 
      tidyr::unite("Y1", X1, X2) %>% 
  tidyr::unite("Y2", X3, X4) %>% 
      tidyr::pivot_longer(cols = dplyr::starts_with("Y"),
                          names_to = "name", values_to = "value") %>% 
  tidyr::separate(value, into = c("期間", "value"), sep = "_") %>% 
  dplyr::mutate(value = stringr::str_remove_all(value, pattern = "[+%]"),
                value = dplyr::na_if(value, "--"),
                value = as.numeric(value)) %>% 
  dplyr::select(-name) %>% 
  tidyr::pivot_wider(names_from = 期間, values_from = value)
```

```{r}
#| code-summary: "シャープレシオ"
xpath <- '//*[@id="main"]/section/section[3]/section[2]/div/div[2]/div/table'

sr <- tidyr::crossing(url, code) %>% 
  dplyr::mutate(site = paste0(url, code)) %>% 
  dplyr::select(code, site) %>% 
  purrr::pmap_df(.f = function (code, site) {
    xml2::read_html(site) %>% 
      rvest::html_element(xpath = xpath) %>% 
      rvest::html_table(header = FALSE) %>% 
      dplyr::slice(-1) %>% 
      dplyr::mutate(code = code)
  })

sr %>% 
  dplyr::rename(期間 = X1, SR = X2, SD = X3, 基準日 = X4) %>% 
  dplyr::mutate(SR = dplyr::na_if(SR, "--"), SD = dplyr::na_if(SD, "--")) %>% 
  dplyr::mutate(SR = as.numeric(SR), SD = as.numeric(SD)) %>% 
  dplyr::select(code, 期間, SR, SD, 基準日)
```


```{r}
#| code-summary: "決算実績"
xpath = '//*[@id="main"]/section/section[3]/section[3]/div/div[2]/div/table'

result <- tidyr::crossing(url, code) %>% 
  dplyr::mutate(site = paste0(url, code)) %>% 
  dplyr::select(code, site) %>% 
  purrr::pmap_df(.f = function (code, site) {
    xml2::read_html(site) %>% 
      rvest::html_element(xpath = xpath) %>% 
      rvest::html_table(header = FALSE) %>% 
      dplyr::slice(-(1:2)) %>%
      dplyr::mutate(code = code)
  })

result %>% 
  dplyr::mutate(dplyr::across(.cols = X1:X4, 
                              ~ dplyr::na_if(.x, "--")))
```


　  

## 金融商品の優劣を測る数値・シャープレシオ

　  

## 練習問題 {.unnumbered}

　  

---
