# はじめに {.unnumbered}

　本資料は[『完全独習 統計学入門』小島寛之著](https://www.diamond.co.jp/book/9784478820094.html)（以降、テキスト）の内容をRで計算する方法を紹介しています。基本的な統計量を求める際に必要となる関数などの解説が中心です。 　

　テキストに記載されているデータの一部をCSVファイルにして利用していますが、データ自体の著作権は原著作者にあります。また、CSVファイルは著作権を侵害する意図で作成したものではありません。

　

## 想定読者 {.unnumbered}

　本書の想定読者は以下に該当する方です。

- Rに関する基本的な知識を有している方
    - データフレーム型や因子型などの変数型の知識
    - 変数の代入・参照方法
    - `tidyverse`の基本的な知識（パイプ演算子など）
- Rで統計量を求めてみたい方

　本書ではRのインストール方法や基本文法などには触れません。


:::{.callout-warning}
## `df_print()`関数について
　本書のコードに出てくる`df_pirnt()`関数はデータフレームを出力フォーマットごとに適切な形式で出力するために定義した関数です。**R**やCRANのパッケージで提供されている関数ではありません。ご自身の環境でコードを実行する際には`df_print()`関数とその直前のパイプ演算子（` %>% `）を削除してから実行してください。  
　例）`x %>% df_print`となっている場合は` %>% df_print()`を削除し`x`を実行してください。
:::

:::{.callout-tip}
## Tip: Code Block Operation
　コードブロックの上にある▼マークをクリックするとコードの表示・非表示を切り替えることができます。また、コードブロック中のパッケージ名や関数名にマウスオーバーした際に下線が表示されるものについては、クリックをするとパッケージや関数の説明ページ（英語）にジャンプできます。
　なお、コードブロック右上にあるアイコンをクリックするとコードをクリップボードにコピーできます。
:::

:::{.callout-tip}
## Tip: Index
　左側に章単位のインデックス（以降、メインインデックス）、右側に現在表示中のページ内のインデックス（以降、サブインデックス）がフローティング表示されます。ウィンドウ幅が狭い場合はメインインデックスは最上段に折りたたみ形式で表示され、サブインデックスは表示幅により表示・非表示が自動的に切り替わります。
　また、メインインデックス最上段のタイトル右側に表示されるトグルスイッチでカラーモードを切り替えることができます。
:::

```{r setup}
#| label: setup
#| echo: false
#| warning: false
#| message: false
source("./R/setup.R")
```

　  

---