---
title: "Chromebook"
subtitle: "Chromebookを買ってみた"
# author: "CC BY-NC-SA 4.0, Sampo Suzuki"
date: "2022/7/9"
lang: ja
format: 
  revealjs: 
    chalkboard: true
    footer: "CC BY-NC-SA 4.0, Sampo Suzuki"
    # slide-number: true
    # smaller: true
    transition: slide # none, fade, slide, convex, concave, zoom
    theme: sky # beige, blood, dark, default, league, moon, night, serif, simple, sky, solarized
---


# はじめに


## 質問
あなたはChromebookを

1. 使っている・使ったことがある  
1. 知っているけど使ったことがない  
1. 名前だけなら知っている  
1. なにそれ？おいしいの？  

回答は[こちら](https://forms.gle/ew2Re3BJdtPGeA9W7)から


# Chromebookとは

## Chromebookの概略
* Googleが開発したChromeOSベースのPC
    * **ARMアーキテクチャ**でも動作可能な軽量設計
    * クラムシェル型／2in1型（フリップ型／デタッチャブル型）／タブレット型と豊富なレパートリー
    * 法人がメインターゲット
    * 在宅勤務拡大をきっかけに個人向けも増えてきた
    * **低価格帯（2～3万円台）**からのラインナップ
* Googleアカウント必須
    * Googleの各種サービスを利用するのが大前提


## ChromeOSの特徴
* シンプルで高速
    * Googleアカウントでログインすれば準備ＯＫ
* セキュリティ・ウィルス対策は組み込み済み
    * アプリはサンドボックス内で独立して動作
    * ポリシーにより期間保証された自動更新あり
* Androidスマホとの様々な連携が可能
    * Smart Lock・インスタントテザリングなど
* Linux（debian）が使える
    * WSL2と異なり**デーモンが動かせる**（VM）


## 三種類のアプリが使える
* Chromeアプリ（プログレッシブウェブアプリへ移行中）
    * Chromeウェブストアからインストール
        * テキストエディタ，電卓アプリ, Zoomなど
* Andoroidアプリ（Playアプリ）
    * Google Playストアからインストール
        * Gboard、ブック・コミック系、Amazon系など
* Linuxアプリ
    * GTKアプリケーション（VS Codeなど）も動作可
      * mozcをインストールすれば日本語入力もOK

# 買ってみて

## 買ってみた理由
* 新しいタブレットが欲しいけどAndroidタブレットはトータルバランスが今一つ
    * CPU，RAM，ストレージ，画面サイズ，解像度，価格
* デタッチャブルならタブレット代わりに使えそう
    * ChromeOSではAndroidアプリが動く機種あり
* 絶賛セール中だった
    * ものによっては1万円台から、デタッチャブルでも2万円台からで、同価格帯のAndroidタブレットよりハイスペックな機種もあり


## 実際に使ってみると
* Androidタブレットとして使ってみると
    * 快適ではあるが、細かい動きが異なる
        * ジェスチャーなどが微妙に異なる
    * 使えない（対応していない）アプリがある
        * ゲーム系は期待しないほうがいい
    * 不安定な部分もある
* デタッチャブルのせいで、かなり重い
    * 脱着式の背面カバースタンド＆キーボードで重量倍


## こんな人に向いている
* Google大好きな人
    * Googleサービスが気軽に使える
    * ログインするだけで準備できる
* 割り切って使える人
    * 使うアプリが限定されているなら気にならない
    * 日本語入力まわりはあまり洗練されてない
* Linuxも使いたい人（x86(amd64)系CPU搭載機を推奨）
    * GitやDockerが使える


## こんな人には向いていない
* 信条のある人
* 高性能・高機能・最新・拡張性を求める人
    * とんがった機種はまずない
* （完全な） Androidタブレットが欲しい人
    * 100%の代替品にはならない
* 常時ネット接続が難しい人
    * 基本的にはスマホと同じ
* ゲームが主目的な人


# 興味がはあるけど…

## ChromeOS Flex
* x86系PCにインストールできるFreeのChromeOS
    * 待望のStable版がリリース（2022/5）
    * 古いPCでも十分使える
        * 第二・三世代Core iでもOKだった（x86-64bit）
* Androidアプリは利用不可（インストール不可）
* Linuxアプリは利用可能（デーモンもOK）
* マルチブート非対応
    * 新しいSSDに入れ替えてからインストールした方が無難


# ＥＮＪＯＹ！

