<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1: 度数分布表とヒストグラムで | Rで学ぶ『完全独習 統計学入門』</title>
  <meta name="description" content="本書はデータ分析勉強会で学んだ成果をまとめたものです" />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1: 度数分布表とヒストグラムで | Rで学ぶ『完全独習 統計学入門』" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="本書はデータ分析勉強会で学んだ成果をまとめたものです" />
  <meta name="github-repo" content="k-metrics/DAWS2022" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1: 度数分布表とヒストグラムで | Rで学ぶ『完全独習 統計学入門』" />
  
  <meta name="twitter:description" content="本書はデータ分析勉強会で学んだ成果をまとめたものです" />
  

<meta name="author" content="Sampo Suzuki, CC 4.0 BY-NC-SA" />


<meta name="date" content="2022-04-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>

<script src="assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="assets/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="assets/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="assets/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link href="assets/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="assets/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="index.html#はじめに">はじめに<span></span></a></li>
<li class="chapter" data-level="1" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html"><i class="fa fa-check"></i><b>1</b> 度数分布表とヒストグラムで<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html#統計を使う"><i class="fa fa-check"></i><b>1.1</b> 統計を使う<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html#ヒストグラムを作る"><i class="fa fa-check"></i><b>1.2</b> ヒストグラムを作る<span></span></a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html#階級を求める"><i class="fa fa-check"></i><b>1.2.1</b> 階級を求める<span></span></a></li>
<li class="chapter" data-level="1.2.2" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html#データを各階級に分類する"><i class="fa fa-check"></i><b>1.2.2</b> データを各階級に分類する<span></span></a></li>
<li class="chapter" data-level="1.2.3" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html#度数を求める"><i class="fa fa-check"></i><b>1.2.3</b> 度数を求める<span></span></a></li>
<li class="chapter" data-level="1.2.4" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html#累積度数相対度数累積相対度数を求める"><i class="fa fa-check"></i><b>1.2.4</b> 累積度数、相対度数、累積相対度数を求める<span></span></a></li>
<li class="chapter" data-level="1.2.5" data-path="度数分布表とヒストグラムで.html"><a href="度数分布表とヒストグラムで.html#階級値を求める"><i class="fa fa-check"></i><b>1.2.5</b> 階級値を求める<span></span></a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Rで学ぶ『完全独習 統計学入門』</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="度数分布表とヒストグラムで" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1:</span> 度数分布表とヒストグラムで<a href="度数分布表とヒストグラムで.html#度数分布表とヒストグラムで" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>　本講で扱うデータはテキストのP16 図表1-1で示されているデータですが、Rで処理しやすいように以下のように一列にまとめて<code>x</code>というデータフレーム型の変数に格納しておきます。</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="度数分布表とヒストグラムで.html#cb1-1" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## # A tibble: 80 × 1
##    height
##     &lt;int&gt;
##  1    151
##  2    154
##  3    160
##  4    160
##  5    163
##  6    156
##  7    158
##  8    156
##  9    154
## 10    160
## # … with 70 more rows</code></pre>
<div id="統計を使う" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> 統計を使う<a href="度数分布表とヒストグラムで.html#統計を使う" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="ヒストグラムを作る" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> ヒストグラムを作る<a href="度数分布表とヒストグラムで.html#ヒストグラムを作る" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>　Rでヒストグラムを描くには<code>hist()</code>関数を使うことで描けます。同時に階級、度数と階級値などを求めることもできます。</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="度数分布表とヒストグラムで.html#cb3-1" aria-hidden="true" tabindex="-1"></a>hist <span class="ot">&lt;-</span> <span class="fu">hist</span>(x<span class="sc">$</span>height, <span class="at">include.lowest =</span> <span class="cn">FALSE</span>, <span class="at">plot =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="R_files/figure-html/unnamed-chunk-3-1.png" width="90%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="度数分布表とヒストグラムで.html#cb4-1" aria-hidden="true" tabindex="-1"></a>hist</span></code></pre></div>
<pre><code>## $breaks
## [1] 140 145 150 155 160 165 170
## 
## $counts
## [1]  1  6 19 30 18  6
## 
## $density
## [1] 0.0025 0.0150 0.0475 0.0750 0.0450 0.0150
## 
## $mids
## [1] 142.5 147.5 152.5 157.5 162.5 167.5
## 
## $xname
## [1] &quot;x$height&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<p>　度数分布表として表にしたい場合は下記のように</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="度数分布表とヒストグラムで.html#cb6-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="度数分布表とヒストグラムで.html#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級を求めて、データを階級ごとに分ける</span></span>
<span id="cb6-3"><a href="度数分布表とヒストグラムで.html#cb6-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">cut</span>(height,</span>
<span id="cb6-4"><a href="度数分布表とヒストグラムで.html#cb6-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height)),</span>
<span id="cb6-5"><a href="度数分布表とヒストグラムで.html#cb6-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">include.lowest =</span> <span class="cn">FALSE</span>, <span class="at">right =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-6"><a href="度数分布表とヒストグラムで.html#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級ごとの度数を求める</span></span>
<span id="cb6-7"><a href="度数分布表とヒストグラムで.html#cb6-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(class) <span class="sc">%&gt;%</span> </span>
<span id="cb6-8"><a href="度数分布表とヒストグラムで.html#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 累積度数、相対度数、累積相対度数を求める</span></span>
<span id="cb6-9"><a href="度数分布表とヒストグラムで.html#cb6-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">cumsum_n =</span> <span class="fu">cumsum</span>(n),</span>
<span id="cb6-10"><a href="度数分布表とヒストグラムで.html#cb6-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">prop =</span> <span class="fu">prop.table</span>(n), <span class="at">cumsum_prop =</span> <span class="fu">cumsum</span>(prop)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-11"><a href="度数分布表とヒストグラムで.html#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級値を求める</span></span>
<span id="cb6-12"><a href="度数分布表とヒストグラムで.html#cb6-12" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">class_value =</span> <span class="fu">as.character</span>(class)) <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="度数分布表とヒストグラムで.html#cb6-13" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">separate</span>(class_value, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;l&quot;</span>, <span class="st">&quot;h&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-14"><a href="度数分布表とヒストグラムで.html#cb6-14" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">l =</span> <span class="fu">as.integer</span>(stringr<span class="sc">::</span><span class="fu">str_remove</span>(l, <span class="st">&quot;[[:punct:]]&quot;</span>)) <span class="sc">+</span> 1L,</span>
<span id="cb6-15"><a href="度数分布表とヒストグラムで.html#cb6-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">h =</span> <span class="fu">as.integer</span>(stringr<span class="sc">::</span><span class="fu">str_remove</span>(h, <span class="st">&quot;[[:punct:]]&quot;</span>)),</span>
<span id="cb6-16"><a href="度数分布表とヒストグラムで.html#cb6-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">mids =</span> (l <span class="sc">+</span> h) <span class="sc">/</span> 2L) <span class="sc">%&gt;%</span></span>
<span id="cb6-17"><a href="度数分布表とヒストグラムで.html#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 変数名を日本語にする</span></span>
<span id="cb6-18"><a href="度数分布表とヒストグラムで.html#cb6-18" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">`</span><span class="at">階級</span><span class="st">`</span> <span class="ot">=</span> class, <span class="st">`</span><span class="at">階級値</span><span class="st">`</span> <span class="ot">=</span> mids,</span>
<span id="cb6-19"><a href="度数分布表とヒストグラムで.html#cb6-19" aria-hidden="true" tabindex="-1"></a>                <span class="st">`</span><span class="at">度数</span><span class="st">`</span> <span class="ot">=</span> n, <span class="st">`</span><span class="at">累積度数</span><span class="st">`</span> <span class="ot">=</span> cumsum_n,</span>
<span id="cb6-20"><a href="度数分布表とヒストグラムで.html#cb6-20" aria-hidden="true" tabindex="-1"></a>                <span class="st">`</span><span class="at">相対度数</span><span class="st">`</span> <span class="ot">=</span> prop, <span class="st">`</span><span class="at">累積相対度数</span><span class="st">`</span> <span class="ot">=</span> cumsum_prop)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["階級"],"name":[1],"type":["fct"],"align":["left"]},{"label":["階級値"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["度数"],"name":[3],"type":["int"],"align":["right"]},{"label":["累積度数"],"name":[4],"type":["int"],"align":["right"]},{"label":["相対度数"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["累積相対度数"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"(140,145]","2":"143","3":"1","4":"1","5":"0.0125","6":"0.0125"},{"1":"(145,150]","2":"148","3":"6","4":"7","5":"0.0750","6":"0.0875"},{"1":"(150,155]","2":"153","3":"19","4":"26","5":"0.2375","6":"0.3250"},{"1":"(155,160]","2":"158","3":"30","4":"56","5":"0.3750","6":"0.7000"},{"1":"(160,165]","2":"163","3":"18","4":"74","5":"0.2250","6":"0.9250"},{"1":"(165,170]","2":"168","3":"6","4":"80","5":"0.0750","6":"1.0000"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div id="階級を求める" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> 階級を求める<a href="度数分布表とヒストグラムで.html#階級を求める" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="度数分布表とヒストグラムで.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height)))</span></code></pre></div>
<pre><code>## [1] 140 145 150 155 160 165 170</code></pre>
<p>　<code>pretty()</code>関数は<code>x</code>引数で指定するデータから階級を求める関数です。<code>n</code>引数で階級を区切る数（階級数）を指定します。ここでは、階級数<code>n</code>はスタージェスの公式から求めています。指定した階級数でデータの範囲を単純に割っている訳ではないことに注意してください。<code>x</code>で指定したデータが階級に収まるように適切な丸め処理を行いますので、指定した階級数どおりの階級が求められるとは限りません。</p>
<p>　スタージェスの公式とは、階級数を<span class="math inline">\(k\)</span>、データのサイズ（数）を<span class="math inline">\(n\)</span>とした場合、下式で定義されます。</p>
<p><span class="math display">\[k = \log_2(n) + 1\]</span></p>
<p>　Rでは<code>nclass.Sturgess()</code>関数が用意されています。</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="度数分布表とヒストグラムで.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">nclass.Sturges</span>(height))</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<p>　
　スタージェスの公式以外にもスコットの選択（<code>nclass.scott()</code>）やフリードマン=ダイアコニスの選択（<code>nclass.FD()</code>）などがあります。</p>
</div>
<div id="データを各階級に分類する" class="section level3 hasAnchor" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> データを各階級に分類する<a href="度数分布表とヒストグラムで.html#データを各階級に分類する" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="度数分布表とヒストグラムで.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">cut</span>(height, <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height))))</span></code></pre></div>
<pre><code>##  [1] (150,155] (150,155] (155,160] (155,160] (160,165] (155,160] (155,160]
##  [8] (155,160] (150,155] (155,160] (150,155] (160,165] (155,160] (160,165]
## [15] (155,160] (160,165] (160,165] (165,170] (145,150] (160,165] (150,155]
## [22] (160,165] (155,160] (160,165] (165,170] (150,155] (155,160] (150,155]
## [29] (155,160] (155,160] (155,160] (145,150] (160,165] (150,155] (155,160]
## [36] (160,165] (150,155] (160,165] (150,155] (150,155] (150,155] (150,155]
## [43] (155,160] (145,150] (145,150] (160,165] (165,170] (150,155] (150,155]
## [50] (165,170] (160,165] (160,165] (145,150] (140,145] (155,160] (160,165]
## [57] (155,160] (155,160] (155,160] (160,165] (165,170] (155,160] (155,160]
## [64] (150,155] (155,160] (155,160] (150,155] (155,160] (150,155] (155,160]
## [71] (145,150] (165,170] (150,155] (155,160] (155,160] (155,160] (160,165]
## [78] (155,160] (155,160] (160,165]
## Levels: (140,145] (145,150] (150,155] (155,160] (160,165] (165,170]</code></pre>
<p>　<code>cut()</code>関数はデータがどの階級に入るかを計算する関数です。<code>breaks</code>引数に任意の階級を指定することも可能です。</p>
<div id="階級の境界値はどちらに含まれるのか" class="section level4 hasAnchor" number="1.2.2.1">
<h4><span class="header-section-number">1.2.2.1</span> 階級の境界値はどちらに含まれるのか？<a href="度数分布表とヒストグラムで.html#階級の境界値はどちらに含まれるのか" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>　<code>cut()</code>関数の出力は、<code>(140,145] (145,150]</code>のように階級間で同じ数値が含まれます。<code>145</code>はどちらの階級に含まれるかは、添えられている括弧で区別できるようになっています。</p>
<blockquote>
<p><code>(140,145]</code></p>
</blockquote>
<p>は「140を超えて145以下」となりますので、次の</p>
<blockquote>
<p><code>(145,150]</code></p>
</blockquote>
<p>は同様に「145を超えて150以下」となりますので、階級間の境界値である<code>145</code>は<code>(140, 145]</code>側に入ります。つまり</p>
<ul>
<li><code>(</code>は「超えて」、<code>)</code>は未満」（境界値を含まない）</li>
<li><code>[</code>は「以上」、<code>]</code>は「以下」（境界値を含む）</li>
</ul>
<p>となっています。<code>cut()</code>関数の<code>include.lowest</code>オプションと<code>right</code>オプションを指定すると下表のように計算結果を変えることができます。</p>
<table>
<thead>
<tr class="header">
<th>option</th>
<th><code>right = TRUE</code></th>
<th><code>right = FALSE</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><code>include.lowest = TRUE</code></strong></td>
<td><strong><code>[</code></strong><code>l,u] ... (l,u]</code></td>
<td><code>[l,u) ... [l,u]</code></td>
</tr>
<tr class="even">
<td><strong><code>include.lowest = FALSE</code></strong></td>
<td><strong><code>(</code></strong><code>l,u] ... (l,u]</code></td>
<td><code>[l,u) ... [l,u)</code></td>
</tr>
</tbody>
</table>
<p>　例えば最大値と最小値を境界値として含む階級を指定した場合、<code>include.lowest = FALSE, right = FALSE</code>と指定すると最大値が階級に含まれなくなります。</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="度数分布表とヒストグラムで.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">cut</span>(height, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">143</span>, <span class="dv">155</span>, <span class="dv">169</span>),</span>
<span id="cb13-2"><a href="度数分布表とヒストグラムで.html#cb13-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">include.lowest =</span> <span class="cn">FALSE</span>, <span class="at">right =</span> <span class="cn">FALSE</span>))</span></code></pre></div>
<pre><code>##  [1] [143,155) [143,155) [155,169) [155,169) [155,169) [155,169) [155,169)
##  [8] [155,169) [143,155) [155,169) [143,155) [155,169) [155,169) [155,169)
## [15] [155,169) [155,169) [155,169) &lt;NA&gt;      [143,155) [155,169) [143,155)
## [22] [155,169) [155,169) [155,169) [155,169) [143,155) [155,169) [155,169)
## [29] [155,169) [155,169) [155,169) [143,155) [155,169) [155,169) [155,169)
## [36] [155,169) [143,155) [155,169) [143,155) [143,155) [143,155) [155,169)
## [43] [155,169) [143,155) [143,155) [155,169) &lt;NA&gt;      [143,155) [155,169)
## [50] [155,169) [155,169) [155,169) [143,155) [143,155) [155,169) [155,169)
## [57] [155,169) [155,169) [155,169) [155,169) [155,169) [155,169) [155,169)
## [64] [143,155) [155,169) [155,169) [143,155) [155,169) [143,155) [155,169)
## [71] [143,155) [155,169) [143,155) [155,169) [155,169) [155,169) [155,169)
## [78] [155,169) [155,169) [155,169)
## Levels: [143,155) [155,169)</code></pre>
<p>　逆に<code>include.lowest = FALSE, right = TRUE</code>と指定すると最小値が階級に含まれなくなります。</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="度数分布表とヒストグラムで.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">cut</span>(height, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">143</span>, <span class="dv">155</span>, <span class="dv">169</span>),</span>
<span id="cb15-2"><a href="度数分布表とヒストグラムで.html#cb15-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">include.lowest =</span> <span class="cn">FALSE</span>, <span class="at">right =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>##  [1] (143,155] (143,155] (155,169] (155,169] (155,169] (155,169] (155,169]
##  [8] (155,169] (143,155] (155,169] (143,155] (155,169] (155,169] (155,169]
## [15] (155,169] (155,169] (155,169] (155,169] (143,155] (155,169] (143,155]
## [22] (155,169] (155,169] (155,169] (155,169] (143,155] (155,169] (143,155]
## [29] (155,169] (155,169] (155,169] (143,155] (155,169] (143,155] (155,169]
## [36] (155,169] (143,155] (155,169] (143,155] (143,155] (143,155] (143,155]
## [43] (155,169] (143,155] (143,155] (155,169] (155,169] (143,155] (143,155]
## [50] (155,169] (155,169] (155,169] (143,155] &lt;NA&gt;      (155,169] (155,169]
## [57] (155,169] (155,169] (155,169] (155,169] (155,169] (155,169] (155,169]
## [64] (143,155] (155,169] (155,169] (143,155] (155,169] (143,155] (155,169]
## [71] (143,155] (155,169] (143,155] (155,169] (155,169] (155,169] (155,169]
## [78] (155,169] (155,169] (155,169]
## Levels: (143,155] (155,169]</code></pre>
</div>
</div>
<div id="度数を求める" class="section level3 hasAnchor" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> 度数を求める<a href="度数分布表とヒストグラムで.html#度数を求める" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>　<code>dplyr::count()</code>関数は<code>table()</code>関数と同様、個数を数える関数です。<code>table()</code>関数の計算対象はベクトル型ですが、<code>dplyr::count()</code>関数はデータフレーム型が計算対象になります。</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="度数分布表とヒストグラムで.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">table</span>(<span class="fu">cut</span>(height, <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height)))))</span></code></pre></div>
<pre><code>## 
## (140,145] (145,150] (150,155] (155,160] (160,165] (165,170] 
##         1         6        19        30        18         6</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="度数分布表とヒストグラムで.html#cb19-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="度数分布表とヒストグラムで.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級を求めて、データを階級ごとに分ける</span></span>
<span id="cb19-3"><a href="度数分布表とヒストグラムで.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">cut</span>(height,</span>
<span id="cb19-4"><a href="度数分布表とヒストグラムで.html#cb19-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height)))) <span class="sc">%&gt;%</span> </span>
<span id="cb19-5"><a href="度数分布表とヒストグラムで.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級ごとの度数を求める</span></span>
<span id="cb19-6"><a href="度数分布表とヒストグラムで.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(class)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   class         n
##   &lt;fct&gt;     &lt;int&gt;
## 1 (140,145]     1
## 2 (145,150]     6
## 3 (150,155]    19
## 4 (155,160]    30
## 5 (160,165]    18
## 6 (165,170]     6</code></pre>
</div>
<div id="累積度数相対度数累積相対度数を求める" class="section level3 hasAnchor" number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> 累積度数、相対度数、累積相対度数を求める<a href="度数分布表とヒストグラムで.html#累積度数相対度数累積相対度数を求める" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>　<code>cumsum()</code>関数は累積和を計算する関数です。</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="度数分布表とヒストグラムで.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">cumsum</span>(<span class="fu">table</span>(<span class="fu">cut</span>(height, <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height))))))</span></code></pre></div>
<pre><code>## (140,145] (145,150] (150,155] (155,160] (160,165] (165,170] 
##         1         7        26        56        74        80</code></pre>
<p>　<code>prop.table()</code>関数は相対度数を計算する関数です。</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="度数分布表とヒストグラムで.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="fu">cut</span>(height, <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height))))))</span></code></pre></div>
<pre><code>## 
## (140,145] (145,150] (150,155] (155,160] (160,165] (165,170] 
##    0.0125    0.0750    0.2375    0.3750    0.2250    0.0750</code></pre>
<p>　<code>prop.table()</code>関数の計算結果を<code>cumsum()</code>関数に渡すことで相対度数の累積和（累積相対度数）を求めることができます。</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="度数分布表とヒストグラムで.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(x, <span class="fu">cumsum</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="fu">cut</span>(height, <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height)))))))</span></code></pre></div>
<pre><code>## (140,145] (145,150] (150,155] (155,160] (160,165] (165,170] 
##    0.0125    0.0875    0.3250    0.7000    0.9250    1.0000</code></pre>
</div>
<div id="階級値を求める" class="section level3 hasAnchor" number="1.2.5">
<h3><span class="header-section-number">1.2.5</span> 階級値を求める<a href="度数分布表とヒストグラムで.html#階級値を求める" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>　階級値は階級の文字列から下限と上限の境界値を抜き出し、単純に下式で平均値を求めています。</p>
<p><span class="math display">\[\frac{(\mbox{下限} + 1) + \mbox{上限}}{2}\]</span></p>
<p>　手順としては以下のようにしています。</p>
<ol style="list-style-type: decimal">
<li><code>as.character()</code>関数で 階級（<code>class</code>）を文字型に変換し、新しい変数（<code>class_value</code>）を作成する<br />
</li>
<li><code>tidyr::separate()</code>関数で文字型の変数（<code>class_value</code>）を<code>,</code>の前後で二つの変数（<code>l</code>, <code>h</code>）に分割する<br />
</li>
<li><code>stringr::str_remove</code>関数で二つの変数（<code>l</code>, <code>h</code>）から<code>(</code>や<code>]</code>を取り除き<code>as.numeric()</code>関数で文字列から数値に変換する<br />
</li>
<li>数値に変換された二つの変数から（<code>l</code>, <code>h</code>）平均値を求める</li>
</ol>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="度数分布表とヒストグラムで.html#cb27-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="度数分布表とヒストグラムで.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級を求めて、データを階級ごとに分ける</span></span>
<span id="cb27-3"><a href="度数分布表とヒストグラムで.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">cut</span>(height,</span>
<span id="cb27-4"><a href="度数分布表とヒストグラムで.html#cb27-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">breaks =</span> <span class="fu">pretty</span>(height, <span class="at">n =</span> <span class="fu">nclass.Sturges</span>(height)),</span>
<span id="cb27-5"><a href="度数分布表とヒストグラムで.html#cb27-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">include.lowest =</span> <span class="cn">FALSE</span>, <span class="at">right =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-6"><a href="度数分布表とヒストグラムで.html#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級ごとの度数を求める</span></span>
<span id="cb27-7"><a href="度数分布表とヒストグラムで.html#cb27-7" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(class) <span class="sc">%&gt;%</span> </span>
<span id="cb27-8"><a href="度数分布表とヒストグラムで.html#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 階級値を求める</span></span>
<span id="cb27-9"><a href="度数分布表とヒストグラムで.html#cb27-9" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">class_value =</span> <span class="fu">as.character</span>(class)) <span class="sc">%&gt;%</span> </span>
<span id="cb27-10"><a href="度数分布表とヒストグラムで.html#cb27-10" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">separate</span>(class_value, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;l&quot;</span>, <span class="st">&quot;h&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-11"><a href="度数分布表とヒストグラムで.html#cb27-11" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">l =</span> <span class="fu">as.numeric</span>(stringr<span class="sc">::</span><span class="fu">str_remove</span>(l, <span class="st">&quot;[[:punct:]]&quot;</span>)),</span>
<span id="cb27-12"><a href="度数分布表とヒストグラムで.html#cb27-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">h =</span> <span class="fu">as.numeric</span>(stringr<span class="sc">::</span><span class="fu">str_remove</span>(h, <span class="st">&quot;[[:punct:]]&quot;</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb27-13"><a href="度数分布表とヒストグラムで.html#cb27-13" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">mids =</span> ((l <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">+</span> h) <span class="sc">/</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   class         n     l     h  mids
##   &lt;fct&gt;     &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 (140,145]     1   140   145   143
## 2 (145,150]     6   145   150   148
## 3 (150,155]    19   150   155   153
## 4 (155,160]    30   155   160   158
## 5 (160,165]    18   160   165   163
## 6 (165,170]     6   165   170   168</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "night",
"family": "serif",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
